// Copyright 2019 Denisov Vladislav
#ifndef MODULES_TASK_1_DENISOV_V_COUNT_FREQUENCY_CHAR_IN_STR_COUNT_FREQUENCY_CHAR_IN_STR_H_
#define MODULES_TASK_1_DENISOV_V_COUNT_FREQUENCY_CHAR_IN_STR_COUNT_FREQUENCY_CHAR_IN_STR_H_

#include <string>

void getRandomStr(int strSize);
int getCountFreqCharInStr(std::string str, char ch);

#endif  // MODULES_TASK_1_DENISOV_V_COUNT_FREQUENCY_CHAR_IN_STR_COUNT_FREQUENCY_CHAR_IN_STR_H_
